sudo: required
services:
  - docker

before_install:
  - docker build -t vokrobodo/react-test -f ./client/Dockerfile.dev

script:
  - docker run -e CI=true vokrobodo/react-test npm test

after_success:
  - docker build -t vokrobodo/multi-client ./client
  - docker build -t vokrobodo/multi-nginx ./nginx
  - docker build -t vokrobodo/multi-worker ./worker
  - docker build -t vokrobodo/multi-server ./server

  # login to docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # push images to dockerhub
  - docker push vokrobodo/multi-client
  - docker push vokrobodo/multi-nginx
  - docker push vokrobodo/multi-worker
  - docker push vokrobodo/multi-server

